# Generated by Django 5.2.3 on 2025-11-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('icon', models.CharField(blank=True, max_length=5)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('is_block_only', models.BooleanField(default=False)),
            ],
        ),
    ]
