# Generated by Django 5.2.3 on 2025-11-01 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyblock',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.tag'),
        ),
    ]
