# Generated by Django 5.2.3 on 2025-11-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_studyblock_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyBlock',
        ),
    ]
