# Generated by Django 5.2.3 on 2025-11-01 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_tag'),
        ('schedule', '0004_delete_studyblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_gregorian', models.DateField()),
                ('date_hijri', models.CharField(max_length=20)),
                ('day_of_week', models.CharField(max_length=10)),
                ('page_start', models.PositiveIntegerField()),
                ('page_end', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.tag')),
            ],
        ),
    ]
