# Generated by Django 5.2.3 on 2025-10-24 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('total_pages', models.IntegerField()),
                ('duration_days', models.IntegerField()),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StudyBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_gregorian', models.DateField()),
                ('date_hijri', models.CharField(max_length=20)),
                ('day_of_week', models.CharField(max_length=10)),
                ('page_start', models.IntegerField()),
                ('page_end', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.book')),
            ],
        ),
    ]
